In [1]:
import pandas as pd 
import numpy as np

In [2]:
df=pd.read_csv("DataCoSupplyChainDataset.csv", encoding='latin1')

In [3]:
df.shape

(180519, 53)

In [4]:
df.columns.to_list()

['Type',
 'Days for shipping (real)',
 'Days for shipment (scheduled)',
 'Benefit per order',
 'Sales per customer',
 'Delivery Status',
 'Late_delivery_risk',
 'Category Id',
 'Category Name',
 'Customer City',
 'Customer Country',
 'Customer Email',
 'Customer Fname',
 'Customer Id',
 'Customer Lname',
 'Customer Password',
 'Customer Segment',
 'Customer State',
 'Customer Street',
 'Customer Zipcode',
 'Department Id',
 'Department Name',
 'Latitude',
 'Longitude',
 'Market',
 'Order City',
 'Order Country',
 'Order Customer Id',
 'order date (DateOrders)',
 'Order Id',
 'Order Item Cardprod Id',
 'Order Item Discount',
 'Order Item Discount Rate',
 'Order Item Id',
 'Order Item Product Price',
 'Order Item Profit Ratio',
 'Order Item Quantity',
 'Sales',
 'Order Item Total',
 'Order Profit Per Order',
 'Order Region',
 'Order State',
 'Order Status',
 'Order Zipcode',
 'Product Card Id',
 'Product Category Id',
 'Product Description',
 'Product Image',
 'Product Name',
 'Product Price',
 'Product Status',
 'shipping date (DateOrders)',
 'Shipping Mode']

In [5]:
pd.set_option('display.max_columns', None)

In [6]:
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,Customer Country,Customer Email,Customer Fname,Customer Id,Customer Lname,Customer Password,Customer Segment,Customer State,Customer Street,Customer Zipcode,Department Id,Department Name,Latitude,Longitude,Market,Order City,Order Country,Order Customer Id,order date (DateOrders),Order Id,Order Item Cardprod Id,Order Item Discount,Order Item Discount Rate,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Cally,20755,Holloway,XXXXXXXXX,Consumer,PR,5365 Noble Nectar Island,725.0,2,Fitness,18.251453,-66.037056,Pacific Asia,Bekasi,Indonesia,20755,1/31/2018 22:56,77202,1360,13.110000,0.04,180517,327.75,0.29,1,327.75,314.640015,91.250000,Southeast Asia,Java Occidental,COMPLETE,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Irene,19492,Luna,XXXXXXXXX,Consumer,PR,2679 Rustic Loop,725.0,2,Fitness,18.279451,-66.037064,Pacific Asia,Bikaner,India,19492,1/13/2018 12:27,75939,1360,16.389999,0.05,179254,327.75,-0.80,1,327.75,311.359985,-249.089996,South Asia,Rajastán,PENDING,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,EE. UU.,XXXXXXXXX,Gillian,19491,Maldonado,XXXXXXXXX,Consumer,CA,8510 Round Bear Gate,95125.0,2,Fitness,37.292233,-121.881279,Pacific Asia,Bikaner,India,19491,1/13/2018 12:06,75938,1360,18.030001,0.06,179253,327.75,-0.80,1,327.75,309.720001,-247.779999,South Asia,Rajastán,CLOSED,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,EE. UU.,XXXXXXXXX,Tana,19490,Tate,XXXXXXXXX,Home Office,CA,3200 Amber Bend,90027.0,2,Fitness,34.125946,-118.291016,Pacific Asia,Townsville,Australia,19490,1/13/2018 11:45,75937,1360,22.940001,0.07,179252,327.75,0.08,1,327.75,304.809998,22.860001,Oceania,Queensland,COMPLETE,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Orli,19489,Hendricks,XXXXXXXXX,Corporate,PR,8671 Iron Anchor Corners,725.0,2,Fitness,18.253769,-66.037048,Pacific Asia,Townsville,Australia,19489,1/13/2018 11:24,75936,1360,29.500000,0.09,179251,327.75,0.45,1,327.75,298.250000,134.210007,Oceania,Queensland,PENDING_PAYMENT,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [7]:
df.tail()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,Customer Country,Customer Email,Customer Fname,Customer Id,Customer Lname,Customer Password,Customer Segment,Customer State,Customer Street,Customer Zipcode,Department Id,Department Name,Latitude,Longitude,Market,Order City,Order Country,Order Customer Id,order date (DateOrders),Order Id,Order Item Cardprod Id,Order Item Discount,Order Item Discount Rate,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
180514,CASH,4,4,40.000000,399.980011,Shipping on time,0,45,Fishing,Brooklyn,EE. UU.,XXXXXXXXX,Maria,1005,Peterson,XXXXXXXXX,Home Office,NY,1322 Broad Glade,11207.0,7,Fan Shop,40.640930,-73.942711,Pacific Asia,Shanghái,China,1005,1/16/2016 3:40,26043,1004,0.0,0.00,65177,399.980011,0.10,1,399.980011,399.980011,40.000000,Eastern Asia,Shanghái,CLOSED,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 3:40,Standard Class
180515,DEBIT,3,2,-613.770019,395.980011,Late delivery,1,45,Fishing,Bakersfield,EE. UU.,XXXXXXXXX,Ronald,9141,Clark,XXXXXXXXX,Corporate,CA,7330 Broad Apple Moor,93304.0,7,Fan Shop,35.362545,-119.018700,Pacific Asia,Hirakata,Japón,9141,1/16/2016 1:34,26037,1004,4.0,0.01,65161,399.980011,-1.55,1,399.980011,395.980011,-613.770019,Eastern Asia,Osaka,COMPLETE,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 1:34,Second Class
180516,TRANSFER,5,4,141.110001,391.980011,Late delivery,1,45,Fishing,Bristol,EE. UU.,XXXXXXXXX,John,291,Smith,XXXXXXXXX,Corporate,CT,97 Burning Landing,6010.0,7,Fan Shop,41.629959,-72.967155,Pacific Asia,Adelaide,Australia,291,1/15/2016 21:00,26024,1004,8.0,0.02,65129,399.980011,0.36,1,399.980011,391.980011,141.110001,Oceania,Australia del Sur,PENDING,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 21:00,Standard Class
180517,PAYMENT,3,4,186.229996,387.980011,Advance shipping,0,45,Fishing,Caguas,Puerto Rico,XXXXXXXXX,Mary,2813,Smith,XXXXXXXXX,Consumer,PR,2585 Silent Autumn Landing,725.0,7,Fan Shop,18.213350,-66.370575,Pacific Asia,Adelaide,Australia,2813,1/15/2016 20:18,26022,1004,12.0,0.03,65126,399.980011,0.48,1,399.980011,387.980011,186.229996,Oceania,Australia del Sur,PENDING_PAYMENT,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/18/2016 20:18,Standard Class
180518,PAYMENT,4,4,168.949997,383.980011,Shipping on time,0,45,Fishing,Caguas,Puerto Rico,XXXXXXXXX,Andrea,7547,Ortega,XXXXXXXXX,Consumer,PR,697 Little Meadow,725.0,7,Fan Shop,18.290380,-66.370613,Pacific Asia,Nagercoil,India,7547,1/15/2016 18:54,26018,1004,16.0,0.04,65113,399.980011,0.44,1,399.980011,383.980011,168.949997,South Asia,Tamil Nadu,PENDING_PAYMENT,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 18:54,Standard Class

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  object
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  object
 48  Product Name                   180519 non-null  object
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  object
 52  Shipping Mode                  180519 non-null  object
dtypes: float64(15), int64(14), object(24)
memory usage: 73.0+ MB

In [9]:
df.isnull().sum().sort_values(ascending=False)

Product Description              180519
Order Zipcode                    155679
Customer Lname                        8
Customer Zipcode                      3
Type                                  0
Order Profit Per Order                0
Order Item Cardprod Id                0
Order Item Discount                   0
Order Item Discount Rate              0
Order Item Id                         0
Order Item Product Price              0
Order Item Profit Ratio               0
Order Item Quantity                   0
Sales                                 0
Order Item Total                      0
Order Region                          0
order date (DateOrders)               0
Order State                           0
Order Status                          0
Product Card Id                       0
Product Category Id                   0
Product Image                         0
Product Name                          0
Product Price                         0
Product Status                        0
shipping date (DateOrders)            0
Order Id                              0
Order Country                         0
Order Customer Id                     0
Customer Fname                        0
Days for shipment (scheduled)         0
Benefit per order                     0
Sales per customer                    0
Delivery Status                       0
Late_delivery_risk                    0
Category Id                           0
Category Name                         0
Customer City                         0
Customer Country                      0
Customer Email                        0
Customer Id                           0
Days for shipping (real)              0
Customer Password                     0
Customer Segment                      0
Customer State                        0
Customer Street                       0
Department Id                         0
Department Name                       0
Latitude                              0
Longitude                             0
Market                                0
Order City                            0
Shipping Mode                         0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df["Order Id"].duplicated().sum()

np.int64(114767)

In [12]:
df.dtypes

Type                              object
Days for shipping (real)           int64
Days for shipment (scheduled)      int64
Benefit per order                float64
Sales per customer               float64
Delivery Status                   object
Late_delivery_risk                 int64
Category Id                        int64
Category Name                     object
Customer City                     object
Customer Country                  object
Customer Email                    object
Customer Fname                    object
Customer Id                        int64
Customer Lname                    object
Customer Password                 object
Customer Segment                  object
Customer State                    object
Customer Street                   object
Customer Zipcode                 float64
Department Id                      int64
Department Name                   object
Latitude                         float64
Longitude                        float64
Market                            object
Order City                        object
Order Country                     object
Order Customer Id                  int64
order date (DateOrders)           object
Order Id                           int64
Order Item Cardprod Id             int64
Order Item Discount              float64
Order Item Discount Rate         float64
Order Item Id                      int64
Order Item Product Price         float64
Order Item Profit Ratio          float64
Order Item Quantity                int64
Sales                            float64
Order Item Total                 float64
Order Profit Per Order           float64
Order Region                      object
Order State                       object
Order Status                      object
Order Zipcode                    float64
Product Card Id                    int64
Product Category Id                int64
Product Description              float64
Product Image                     object
Product Name                      object
Product Price                    float64
Product Status                     int64
shipping date (DateOrders)        object
Shipping Mode                     object
dtype: object

In [13]:
df['order date (DateOrders)']= pd.to_datetime(df['order date (DateOrders)'])
df['shipping date (DateOrders)']= pd.to_datetime(df['shipping date (DateOrders)'])

In [14]:
df.dtypes

Type                                     object
Days for shipping (real)                  int64
Days for shipment (scheduled)             int64
Benefit per order                       float64
Sales per customer                      float64
Delivery Status                          object
Late_delivery_risk                        int64
Category Id                               int64
Category Name                            object
Customer City                            object
Customer Country                         object
Customer Email                           object
Customer Fname                           object
Customer Id                               int64
Customer Lname                           object
Customer Password                        object
Customer Segment                         object
Customer State                           object
Customer Street                          object
Customer Zipcode                        float64
Department Id                             int64
Department Name                          object
Latitude                                float64
Longitude                               float64
Market                                   object
Order City                               object
Order Country                            object
Order Customer Id                         int64
order date (DateOrders)          datetime64[ns]
Order Id                                  int64
Order Item Cardprod Id                    int64
Order Item Discount                     float64
Order Item Discount Rate                float64
Order Item Id                             int64
Order Item Product Price                float64
Order Item Profit Ratio                 float64
Order Item Quantity                       int64
Sales                                   float64
Order Item Total                        float64
Order Profit Per Order                  float64
Order Region                             object
Order State                              object
Order Status                             object
Order Zipcode                           float64
Product Card Id                           int64
Product Category Id                       int64
Product Description                     float64
Product Image                            object
Product Name                             object
Product Price                           float64
Product Status                            int64
shipping date (DateOrders)       datetime64[ns]
Shipping Mode                            object
dtype: object

In [15]:
df.describe().T

,count,mean,min,25%,50%,75%,max,std
Days for shipping (real),180519.0,3.497654,0.0,2.0,3.0,5.0,6.0,1.623722
Days for shipment (scheduled),180519.0,2.931847,0.0,2.0,4.0,4.0,4.0,1.374449
Benefit per order,180519.0,21.974989,-4274.97998,7.0,31.52,64.800003,911.799988,104.433526
Sales per customer,180519.0,183.107609,7.49,104.379997,163.990005,247.399994,1939.98999,120.04367
Late_delivery_risk,180519.0,0.548291,0.0,0.0,1.0,1.0,1.0,0.497664
Category Id,180519.0,31.851451,2.0,18.0,29.0,45.0,76.0,15.640064
Customer Id,180519.0,6691.379495,1.0,3258.5,6457.0,9779.0,20757.0,4162.918106
Customer Zipcode,180516.0,35921.126914,603.0,725.0,19380.0,78207.0,99205.0,37542.461122
Department Id,180519.0,5.44346,2.0,4.0,5.0,7.0,12.0,1.629246
Latitude,180519.0,29.719955,-33.937553,18.265432,33.144863,39.279617,48.781933,9.813646
Longitude,180519.0,-84.915675,-158.025986,-98.446312,-76.847908,-66.370583,115.263077,21.433241
Order Customer Id,180519.0,6691.379495,1.0,3258.5,6457.0,9779.0,20757.0,4162.918106
order date (DateOrders),180519,2016-06-12 17:47:04.669868544,2015-01-01 00:00:00,2015-09-21 13:49:00,2016-06-11 13:06:00,2017-03-01 08:42:00,2018-01-31 23:38:00,NaN
Order Id,180519.0,36221.894903,1.0,18057.0,36140.0,54144.0,77204.0,21045.379569
Order Item Cardprod Id,180519.0,692.509764,19.0,403.0,627.0,1004.0,1363.0,336.446807
Order Item Discount,180519.0,20.664741,0.0,5.4,14.0,29.99,500.0,21.800901
Order Item Discount Rate,180519.0,0.101668,0.0,0.04,0.1,0.16,0.25,0.070415
Order Item Id,180519.0,90260.0,1.0,45130.5,90260.0,135389.5,180519.0,52111.490959
Order Item Product Price,180519.0,141.23255,9.99,50.0,59.990002,199.990005,1999.98999,139.732492
Order Item Profit Ratio,180519.0,0.120647,-2.75,0.08,0.27,0.36,0.5,0.466796
Order Item Quantity,180519.0,2.127638,1.0,1.0,1.0,3.0,5.0,1.453451
Sales,180519.0,203.772096,9.99,119.980003,199.919998,299.950012,1999.98999,132.273077
Order Item Total,180519.0,183.107609,7.49,104.379997,163.990005,247.399994,1939.98999,120.04367
Order Profit Per Order,180519.0,21.974989,-4274.97998,7.0,31.52,64.800003,911.799988,104.433526
Order Zipcode,24840.0,55426.132327,1040.0,23464.0,59405.0,90008.0,99301.0,31919.279101
Product Card Id,180519.0,692.509764,19.0,403.0,627.0,1004.0,1363.0,336.446807
Product Category Id,180519.0,31.851451,2.0,18.0,29.0,45.0,76.0,15.640064
Product Description,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Product Price,180519.0,141.23255,9.99,50.0,59.990002,199.990005,1999.98999,139.732492
Product Status,180519.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
shipping date (DateOrders),180519,2016-06-16 05:45:23.202433024,2015-01-03 00:00:00,2015-09-25 06:59:00,2016-06-15 08:32:00,2017-03-04 21:29:00,2018-02-06 22:14:00,NaN

In [16]:
late_rate= df["Late_delivery_risk"].mean() * 100

print(round(late_rate, 2))

54.83

In [17]:
df['Delivery Status'].value_counts()

Delivery Status
Late delivery        98977
Advance shipping     41592
Shipping on time     32196
Shipping canceled     7754
Name: count, dtype: int64

In [18]:
df["shipping_gap"] = (
    df["Days for shipping (real)"]
    - df["Days for shipment (scheduled)"]
)

In [19]:
df["shipping_gap"].describe()

count    180519.000000
mean          0.565807
std           1.490966
min          -2.000000
25%           0.000000
50%           1.000000
75%           1.000000
max           4.000000
Name: shipping_gap, dtype: float64

In [20]:
# Which shipping mode has the biggest problem?

Shipping_analysis= (
    df.groupby('Shipping Mode')
        .agg(
            orders = ('Order Id', 'nunique'),
            late_rate=("Late_delivery_risk", "mean"),
            avg_actual_days=("Days for shipping (real)", "mean"),
            avg_scheduled_days=("Days for shipment (scheduled)", "mean")

        ) 
)

Shipping_analysis['late_rate'] *= 100

Shipping_analysis.sort_values(
    'late_rate', ascending= False
)

                orders  late_rate  avg_actual_days  avg_scheduled_days
Shipping Mode
First Class      10079  95.322499         2.000000                 1.0
Second Class     12778  76.632781         3.990828                 2.0
Same Day          3571  45.743042         0.478279                 0.0
Standard Class   39324  38.071683         3.995907                 4.0

In [21]:
df.groupby(
    ["Shipping Mode", "Market"]
)["Late_delivery_risk"].mean().mul(100)

Shipping Mode   Market
First Class     Africa          96.988998
                Europe          95.818550
                LATAM           94.737510
                Pacific Asia    95.080146
                USCA            95.159681
Same Day        Africa          44.011976
                Europe          46.429866
                LATAM           48.037736
                Pacific Asia    43.530997
                USCA            44.421199
Second Class    Africa          77.402957
                Europe          77.030727
                LATAM           75.560922
                Pacific Asia    77.243157
                USCA            76.650343
Standard Class  Africa          38.214033
                Europe          38.009415
                LATAM           37.886822
                Pacific Asia    38.473115
                USCA            37.857330
Name: Late_delivery_risk, dtype: float64

In [22]:
df.groupby(
    ["Shipping Mode", "Order Region"]
)["Late_delivery_risk"].mean().mul(100)

Shipping Mode   Order Region
First Class     Canada              92.391304
                Caribbean           94.886840
                Central Africa      92.666667
                Central America     95.504336
                Central Asia       100.000000
                                      ...
Standard Class  US Center           37.625814
                West Africa         37.455986
                West Asia           37.542469
                West of USA         37.225820
                Western Europe      38.382501
Name: Late_delivery_risk, Length: 92, dtype: float64

In [23]:
df.groupby(
    ["Shipping Mode", "Category Name"]
)["Late_delivery_risk"].mean().mul(100)

Shipping Mode   Category Name
First Class     Accessories            95.862069
                As Seen on  TV!        90.000000
                Baby                   97.058824
                Baseball & Softball    98.095238
                Basketball             81.250000
                                         ...
Standard Class  Video Games            39.615385
                Water Sports           37.735643
                Women's Apparel        37.745489
                Women's Clothing       39.083558
                Women's Golf Clubs     36.363636
Name: Late_delivery_risk, Length: 199, dtype: float64

In [24]:
df.groupby("Shipping Mode")["shipping_gap"].mean()

Shipping Mode
First Class       1.000000
Same Day          0.478279
Second Class      1.990828
Standard Class   -0.004093
Name: shipping_gap, dtype: float64

In [25]:
df['year']= df['order date (DateOrders)'].dt.year
df['month']= df['order date (DateOrders)'].dt.month
df['days']= df['order date (DateOrders)'].dt.day

In [26]:
df[['year','month','days']].head()

   year  month  days
0  2018      1    31
1  2018      1    13
2  2018      1    13
3  2018      1    13
4  2018      1    13

In [27]:
df.groupby(
    ["Shipping Mode", "year"]
)["Late_delivery_risk"].mean().mul(100)

Shipping Mode   year
First Class     2015    95.761398
                2016    95.486111
                2017    94.489465
                2018    97.865854
Same Day        2015    44.585219
                2016    43.205166
                2017    50.224525
                2018    41.666667
Second Class    2015    77.052528
                2016    76.786594
                2017    75.936655
                2018    77.078652
Standard Class  2015    37.943935
                2016    38.400086
                2017    37.799148
                2018    39.105691
Name: Late_delivery_risk, dtype: float64

In [28]:
df.groupby(
    ["Shipping Mode", "month"]
)["Late_delivery_risk"].mean().mul(100)

Shipping Mode   month
First Class     1        95.801373
                2        94.512195
                3        95.846154
                4        95.218945
                5        92.593957
                6        96.665164
                7        95.170097
                8        96.250987
                9        95.754328
                10       95.965828
                11       96.075269
                12       94.402634
Same Day        1        46.273292
                2        45.465839
                3        48.534584
                4        43.918919
                5        46.976744
                6        48.552632
                7        41.911765
                8        50.440252
                9        43.456790
                10       46.952909
                11       42.260062
                12       44.508671
Second Class    1        77.017448
                2        75.462478
                3        76.703224
                4        76.204332
                5        77.391010
                6        74.067909
                7        78.208074
                8        76.852699
                9        76.869623
                10       74.833055
                11       77.502002
                12       78.493266
Standard Class  1        38.479941
                2        38.764753
                3        37.876705
                4        38.071337
                5        37.466907
                6        38.892529
                7        37.231554
                8        37.811694
                9        38.641534
                10       37.761966
                11       37.660085
                12       38.084544
Name: Late_delivery_risk, dtype: float64

In [29]:
df.groupby(
    ["Shipping Mode", "days"]
)["Late_delivery_risk"].mean().mul(100)

Shipping Mode   days
First Class     1       93.958076
                2       95.423564
                3       94.192186
                4       97.677120
                5       95.194274
                          ...
Standard Class  27      40.567164
                28      38.088526
                29      39.459795
                30      38.051795
                31      35.639029
Name: Late_delivery_risk, Length: 124, dtype: float64

In [30]:
monthly_delivery = (
    df.groupby(["year", "month"])
      .agg(
          orders=("Order Id", "nunique"),
          late_rate=("Late_delivery_risk", "mean"),
          avg_shipping_days=("Days for shipping (real)", "mean")
      )
      .reset_index()
)

monthly_delivery["late_rate"] *= 100

monthly_delivery.head(20)

    year  month  orders  late_rate  avg_shipping_days
0   2015      1    1787  54.114994           3.549042
1   2015      2    1585  54.853034           3.498626
2   2015      3    1781  54.755688           3.491235
3   2015      4    1710  53.843153           3.536676
4   2015      5    1776  55.086802           3.475079
5   2015      6    1725  54.109856           3.522984
6   2015      7    1763  55.463295           3.468202
7   2015      8    1762  55.679879           3.469562
8   2015      9    1706  56.692607           3.528794
9   2015     10    1775  54.809506           3.474161
10  2015     11    1729  54.269341           3.510602
11  2015     12    1805  54.682554           3.464159
12  2016      1    1772  55.576453           3.479782
13  2016      2    1650  54.147936           3.561708
14  2016      3    1764  55.758157           3.471017
15  2016      4    1706  55.228566           3.528939
16  2016      5    1763  55.658242           3.470011
17  2016      6    1690  56.846063           3.544321
18  2016      7    1758  51.932139           3.445994
19  2016      8    1766  55.268091           3.478065

In [31]:
monthly_delivery.sort_values("late_rate", ascending=False).head(10)

    year  month  orders  late_rate  avg_shipping_days
17  2016      6    1690  56.846063           3.544321
8   2015      9    1706  56.692607           3.528794
31  2017      8    1768  56.437323           3.514797
36  2018      1    2123  56.288271           3.504004
23  2016     12    1763  56.063769           3.473145
14  2016      3    1764  55.758157           3.471017
7   2015      8    1762  55.679879           3.469562
16  2016      5    1763  55.658242           3.470011
12  2016      1    1772  55.576453           3.479782
6   2015      7    1763  55.463295           3.468202

In [32]:
yearly_delivery = (
    df.groupby("year")
      .agg(
          orders=("Order Id", "nunique"),
          late_rate=("Late_delivery_risk", "mean"),
          avg_shipping_days=("Days for shipping (real)", "mean")
      )
      .reset_index()
)

yearly_delivery["late_rate"] *= 100

yearly_delivery

   year  orders  late_rate  avg_shipping_days
0  2015   20904  54.863528           3.498803
1  2016   20859  55.069544           3.492294
2  2017   21866  54.447703           3.502350
3  2018    2123  56.288271           3.504004

In [33]:
region_analysis = (
    df.groupby("Order Region")
      .agg(
          orders=("Order Id", "nunique"),
          late_rate=("Late_delivery_risk", "mean"),
          avg_shipping_days=("Days for shipping (real)", "mean")
      )
      .reset_index()
)

region_analysis["late_rate"] *= 100

region_analysis.sort_values(
    "late_rate",
    ascending=False
)

       Order Region  orders  late_rate  avg_shipping_days
2    Central Africa     556  57.960644           3.560525
13       South Asia    3335  56.266977           3.502005
5       East Africa     613  55.939525           3.514579
22   Western Europe   10010  55.848611           3.498432
14   South of  USA     1345  55.772559           3.492707
8    Eastern Europe    1292  55.663265           3.500765
6       East of USA    2323  55.661605           3.500940
15   Southeast Asia    4356  55.529930           3.496698
4      Central Asia     184  55.334539           3.417722
20        West Asia    2022  55.283741           3.486770
18       US Center     1935  55.240360           3.457618
3   Central America    9396  54.754596           3.510462
9      North Africa    1064  54.517327           3.480507
17  Southern Europe    3543  54.384477           3.435797
7      Eastern Asia    3318  54.326923           3.527335
12    South America    4979  54.308671           3.505725
10  Northern Europe    3716  54.044118           3.502349
11          Oceania    4362  54.020497           3.496354
21     West of USA     2667  53.959715           3.504942
16  Southern Africa     398  53.327571           3.446845
1         Caribbean    2806  53.077663           3.507213
19      West Africa    1223  52.840909           3.534091
0            Canada     309  48.800834           3.331595

In [34]:
market_analysis = (
    df.groupby("Market")
      .agg(
          orders=("Order Id", "nunique"),
          late_rate=("Late_delivery_risk", "mean"),
          avg_shipping_days=("Days for shipping (real)", "mean")
      )
      .reset_index()
)

market_analysis["late_rate"] *= 100

market_analysis.sort_values(
    "late_rate",
    ascending=False
)

         Market  orders  late_rate  avg_shipping_days
1        Europe   18561  55.207753           3.487622
3  Pacific Asia   17577  55.046049           3.500509
4          USCA    8579  54.800574           3.484709
0        Africa    3854  54.589289           3.511193
2         LATAM   17181  54.355158           3.508567

In [35]:
mode_region = (
    df.groupby(["Shipping Mode", "Order Region"])
      .agg(
          orders=("Order Id", "nunique"),
          late_rate=("Late_delivery_risk", "mean"),
          avg_shipping_days=("Days for shipping (real)", "mean"),
          avg_scheduled_days=("Days for shipment (scheduled)", "mean")
      )
      .reset_index()
)

mode_region["late_rate"] *= 100

mode_region.sort_values(
    "late_rate",
    ascending=False
).head(20)

,Shipping Mode,Order Region,orders,late_rate,avg_shipping_days,avg_scheduled_days
4,First Class,Central Asia,19,100.000000,2.0,1.0
5,First Class,East Africa,96,98.928571,2.0,1.0
16,First Class,Southern Africa,65,98.484848,2.0,1.0
19,First Class,West Africa,145,97.840173,2.0,1.0
17,First Class,Southern Europe,525,97.207447,2.0,1.0
9,First Class,North Africa,155,97.119342,2.0,1.0
13,First Class,South Asia,543,96.648480,2.0,1.0
18,First Class,US Center,328,96.450304,2.0,1.0
6,First Class,East of USA,357,96.418733,2.0,1.0
8,First Class,Eastern Europe,212,96.048632,2.0,1.0
10,First Class,Northern Europe,551,95.980254,2.0,1.0
3,First Class,Central America,1448,95.504336,2.0,1.0
15,First Class,Southeast Asia,682,95.489691,2.0,1.0
20,First Class,West Asia,329,95.271630,2.0,1.0
22,First Class,Western Europe,1590,95.245826,2.0,1.0
14,First Class,South of USA,197,95.166667,2.0,1.0
1,First Class,Caribbean,415,94.886840,2.0,1.0
7,First Class,Eastern Asia,499,94.822627,2.0,1.0
21,First Class,West of USA,398,93.298520,2.0,1.0
12,First Class,South America,775,93.206404,2.0,1.0

In [36]:
df["shipping_gap"].value_counts().sort_index()

shipping_gap
-2    21666
-1    21700
 0    33753
 1    60647
 2    28718
 3     7052
 4     6983
Name: count, dtype: int64

In [37]:
gap_by_mode = (
    df.groupby("Shipping Mode")["shipping_gap"]
      .agg(["mean", "median", "min", "max"])
      .reset_index()
)

gap_by_mode

    Shipping Mode      mean  median  min  max
0     First Class  1.000000     1.0    1    1
1        Same Day  0.478279     0.0    0    1
2    Second Class  1.990828     2.0    0    4
3  Standard Class -0.004093     0.0   -2    2

In [38]:
delivery_status = (
    df.groupby("Delivery Status")
      .agg(
          records=("Order Id", "count"),
          orders=("Order Id", "nunique"),
          sales=("Sales", "sum"),
          profit=("Order Profit Per Order", "sum")
      )
      .reset_index()
)

delivery_status

     Delivery Status  records  orders         sales        profit
0   Advance shipping    41592   15127  8.518008e+06  9.352253e+05
1      Late delivery    98977   36048  2.012640e+07  2.140052e+06
2  Shipping canceled     7754    2855  1.570305e+06  1.604823e+05
3   Shipping on time    32196   11722  6.570026e+06  7.311437e+05

In [39]:
delivery_profit = (
    df.groupby("Delivery Status")
      .agg(
          orders=("Order Id", "nunique"),
          sales=("Sales", "sum"),
          avg_profit=("Order Profit Per Order", "mean")
      )
      .reset_index()
)

delivery_profit

     Delivery Status  orders         sales  avg_profit
0   Advance shipping   15127  8.518008e+06   22.485701
1      Late delivery   36048  2.012640e+07   21.621707
2  Shipping canceled    2855  1.570305e+06   20.696717
3   Shipping on time   11722  6.570026e+06   22.709146

In [40]:
category_analysis = (
    df.groupby("Category Name")
      .agg(
          orders=("Order Id", "nunique"),
          late_rate=("Late_delivery_risk", "mean"),
          sales=("Sales", "sum"),
          avg_profit=("Order Profit Per Order", "mean")
      )
      .reset_index()
)

category_analysis["late_rate"] *= 100

category_analysis.sort_values(
    "late_rate",
    ascending=False
).head(15)

          Category Name  orders  late_rate          sales  avg_profit
23    Golf Bags & Carts      61  68.852459   10369.390336   29.673279
32             Lacrosse     341  60.058309   39464.789793   12.723878
37         Pet Supplies     492  58.943089   41524.800753    7.295244
8              Cameras      592  58.108108  267607.685032   51.165203
41    Strength Training     111  57.657658   54895.529536    2.993785
1       As Seen on  TV!      68  57.352941   20597.939964   10.506323
36                Music     434  57.142857  113122.097353   33.263410
0           Accessories    1753  56.966292  133671.508825    9.350292
19  Fitness Accessories     307  56.957929   35601.440544   17.017443
5                Books      405  56.543210   12587.399968    2.180272
48     Women's Clothing     650  56.461538  140283.004745   29.389000
6          Boxing & MMA     421  56.264775   85205.411087   20.428771
25          Golf Gloves    1064  56.261682  116695.390423   12.126626
29   Hunting & Shooting     436  56.136364   56848.420072   13.590909
17          Electronics    3061  56.083650  371034.643188   12.956711

In [41]:
yearly_delivery = (
    df.groupby("year")
      .agg(
          orders=("Order Id", "nunique"),
          late_rate=("Late_delivery_risk", "mean"),
          avg_shipping_days=("Days for shipping (real)", "mean")
      )
      .reset_index()
)

yearly_delivery["late_rate"] *= 100

yearly_delivery.sort_values('late_rate', ascending=False)

   year  orders  late_rate  avg_shipping_days
3  2018    2123  56.288271           3.504004
1  2016   20859  55.069544           3.492294
0  2015   20904  54.863528           3.498803
2  2017   21866  54.447703           3.502350

In [42]:
mode_region.sort_values(
    "orders",
    ascending=False
).head(20)

,Shipping Mode,Order Region,orders,late_rate,avg_shipping_days,avg_scheduled_days
91,Standard Class,Western Europe,5933,38.382501,3.998046,4.0
72,Standard Class,Central America,5627,38.528291,4.006919,4.0
81,Standard Class,South America,3001,38.099989,3.991686,4.0
84,Standard Class,Southeast Asia,2622,39.207435,3.996493,4.0
80,Standard Class,Oceania,2601,39.131148,4.013607,4.0
79,Standard Class,Northern Europe,2238,37.872629,3.983909,4.0
86,Standard Class,Southern Europe,2140,36.590106,3.954064,4.0
76,Standard Class,Eastern Asia,2012,37.446328,3.979661,4.0
68,Second Class,Western Europe,1958,77.896285,4.056455,2.0
82,Standard Class,South Asia,1949,38.166925,3.993137,4.0
49,Second Class,Central America,1827,75.004561,3.958219,2.0
70,Standard Class,Caribbean,1695,35.336109,3.960341,4.0
90,Standard Class,West of USA,1602,37.225820,3.968247,4.0
22,First Class,Western Europe,1590,95.245826,2.000000,1.0
3,First Class,Central America,1448,95.504336,2.000000,1.0
75,Standard Class,East of USA,1397,39.782082,4.056174,4.0
89,Standard Class,West Asia,1191,37.542469,3.985277,4.0
87,Standard Class,US Center,1128,37.625814,4.017170,4.0
58,Second Class,South America,939,75.061903,3.999646,2.0
57,Second Class,Oceania,883,76.756757,3.927764,2.0

In [43]:
mode_region.sort_values(
    "late_rate",
    ascending=False
).head(20)

,Shipping Mode,Order Region,orders,late_rate,avg_shipping_days,avg_scheduled_days
4,First Class,Central Asia,19,100.000000,2.0,1.0
5,First Class,East Africa,96,98.928571,2.0,1.0
16,First Class,Southern Africa,65,98.484848,2.0,1.0
19,First Class,West Africa,145,97.840173,2.0,1.0
17,First Class,Southern Europe,525,97.207447,2.0,1.0
9,First Class,North Africa,155,97.119342,2.0,1.0
13,First Class,South Asia,543,96.648480,2.0,1.0
18,First Class,US Center,328,96.450304,2.0,1.0
6,First Class,East of USA,357,96.418733,2.0,1.0
8,First Class,Eastern Europe,212,96.048632,2.0,1.0
10,First Class,Northern Europe,551,95.980254,2.0,1.0
3,First Class,Central America,1448,95.504336,2.0,1.0
15,First Class,Southeast Asia,682,95.489691,2.0,1.0
20,First Class,West Asia,329,95.271630,2.0,1.0
22,First Class,Western Europe,1590,95.245826,2.0,1.0
14,First Class,South of USA,197,95.166667,2.0,1.0
1,First Class,Caribbean,415,94.886840,2.0,1.0
7,First Class,Eastern Asia,499,94.822627,2.0,1.0
21,First Class,West of USA,398,93.298520,2.0,1.0
12,First Class,South America,775,93.206404,2.0,1.0

In [44]:
mode_category = (
    df.groupby(["Shipping Mode", "Category Name"])
      .agg(
          orders=("Order Id", "nunique"),
          late_rate=("Late_delivery_risk", "mean"),
          avg_gap=("shipping_gap", "mean")
      )
      .reset_index()
)

mode_category["late_rate"] *= 100

mode_category.sort_values(
    "late_rate",
    ascending=False
).head(20)

    Shipping Mode        Category Name  orders   late_rate  avg_gap
72       Same Day    Golf Bags & Carts       1  100.000000      1.0
39    First Class               Soccer      15  100.000000      1.0
20    First Class               Garden      73  100.000000      1.0
41    First Class    Strength Training      14  100.000000      1.0
32    First Class             Lacrosse      51  100.000000      1.0
23    First Class    Golf Bags & Carts      19  100.000000      1.0
5     First Class               Books       53  100.000000      1.0
103  Second Class           Basketball       9  100.000000      3.1
26    First Class           Golf Shoes      78   98.717949      1.0
22    First Class         Golf Apparel      58   98.275862      1.0
3     First Class  Baseball & Softball     105   98.095238      1.0
28    First Class               Hockey      98   97.959184      1.0
33    First Class       Men's Clothing      37   97.297297      1.0
24    First Class           Golf Balls     205   97.129187      1.0
2     First Class                Baby       34   97.058824      1.0
40    First Class       Sporting Goods      59   96.610169      1.0
48    First Class     Women's Clothing      88   96.590909      1.0
29    First Class   Hunting & Shooting      57   96.491228      1.0
37    First Class         Pet Supplies      84   96.428571      1.0
13    First Class            Computers      55   96.363636      1.0

In [47]:
customer_segment= (
    df.groupby('Customer Segment')
    .agg(
        order=('Order Id', 'nunique'),
        late_rate=('Late_delivery_risk', 'mean'),
        sales=('Sales', 'sum'),
        profit=('Order Profit Per Order', 'sum')
    )
    .reset_index()
)

customer_segment['late_rate'] *= 100

customer_segment.sort_values('late_rate', ascending=False)

  Customer Segment  order  late_rate         sales        profit
2      Home Office  11777  55.070440  6.520538e+06  6.908403e+05
0         Consumer  34119  54.808350  1.909579e+07  2.073488e+06
1        Corporate  19856  54.722663  1.116841e+07  1.202575e+06

In [48]:
financial_impact = (
    df.groupby("Delivery Status")
      .agg(
          orders=("Order Id", "nunique"),
          sales=("Sales", "sum"),
          profit=("Order Profit Per Order", "sum"),
          avg_profit=("Order Profit Per Order", "mean")
      )
      .reset_index()
)

financial_impact

     Delivery Status  orders         sales        profit  avg_profit
0   Advance shipping   15127  8.518008e+06  9.352253e+05   22.485701
1      Late delivery   36048  2.012640e+07  2.140052e+06   21.621707
2  Shipping canceled    2855  1.570305e+06  1.604823e+05   20.696717
3   Shipping on time   11722  6.570026e+06  7.311437e+05   22.709146

In [49]:
late_orders = df[df["Late_delivery_risk"] == 1]

late_sales = late_orders["Sales"].sum()
total_sales = df["Sales"].sum()

late_sales_share = late_sales / total_sales * 100

print("Late-order sales:", late_sales)
print("Total sales:", total_sales)
print("Late-order sales share:", late_sales_share)

Late-order sales: 20126395.26523882
Total sales: 36784735.01337984
Late-order sales share: 54.71398735893619

In [50]:
country_analysis = (
    df.groupby("Order Country")
      .agg(
          orders=("Order Id", "nunique"),
          late_rate=("Late_delivery_risk", "mean"),
          avg_gap=("shipping_gap", "mean")
      )
      .reset_index()
)

country_analysis["late_rate"] *= 100

country_analysis.sort_values(
    "late_rate",
    ascending=False
).head(20)

           Order Country  orders   late_rate   avg_gap
125  República de Gambia       1  100.000000  2.000000
7                Armenia       1  100.000000  1.000000
144    Sáhara Occidental       1  100.000000  2.000000
24                 Bután       2  100.000000  2.000000
140        Sudán del Sur       2  100.000000  2.200000
88            Luxemburgo       4  100.000000  2.700000
83                  Laos       3  100.000000  1.833333
137          Suazilandia       2  100.000000  2.000000
44               Eritrea       1  100.000000  2.000000
62     Guinea Ecuatorial       2  100.000000  1.500000
49               Estonia      10   96.551724  1.551724
126  República del Congo       5   92.307692  1.000000
46             Eslovenia       3   83.333333  1.833333
64                Guyana       6   78.947368  0.842105
54                 Gabón      12   77.777778  1.111111
153                Túnez      12   77.777778  0.861111
103              Namibia       6   75.000000  0.750000
45            Eslovaquia       8   72.727273  0.818182
151         Turkmenistán      18   69.811321  0.679245
35            Costa Rica      11   69.444444  1.305556

In [51]:
root_cause_summary = (
    df.groupby(["Shipping Mode", "Order Region"])
      .agg(
          orders=("Order Id", "nunique"),
          late_rate=("Late_delivery_risk", "mean"),
          avg_gap=("shipping_gap", "mean"),
          sales=("Sales", "sum"),
          profit=("Order Profit Per Order", "sum")
      )
      .reset_index()
)

root_cause_summary["late_rate"] *= 100

root_cause_summary = root_cause_summary.sort_values(
    ["late_rate", "orders"],
    ascending=[False, False]
)

root_cause_summary.head(20)

,Shipping Mode,Order Region,orders,late_rate,avg_gap,sales,profit
4,First Class,Central Asia,19,100.000000,1.0,11901.370216,997.760045
5,First Class,East Africa,96,98.928571,1.0,55829.011075,8403.180001
16,First Class,Southern Africa,65,98.484848,1.0,37871.120797,4588.460043
19,First Class,West Africa,145,97.840173,1.0,89661.691800,9916.110049
17,First Class,Southern Europe,525,97.207447,1.0,332145.316078,38535.670038
9,First Class,North Africa,155,97.119342,1.0,96183.321984,13672.019967
13,First Class,South Asia,543,96.648480,1.0,260713.514853,23816.769972
18,First Class,US Center,328,96.450304,1.0,191715.863692,24436.020038
6,First Class,East of USA,357,96.418733,1.0,211524.194141,21560.310126
8,First Class,Eastern Europe,212,96.048632,1.0,131587.932664,11071.439992
10,First Class,Northern Europe,551,95.980254,1.0,308814.845886,28384.500046
3,First Class,Central America,1448,95.504336,1.0,883848.836748,97290.150079
15,First Class,Southeast Asia,682,95.489691,1.0,312532.646141,34130.420000
20,First Class,West Asia,329,95.271630,1.0,195131.573831,21383.480039
22,First Class,Western Europe,1590,95.245826,1.0,936797.496738,115193.420123
14,First Class,South of USA,197,95.166667,1.0,122223.762395,14772.400009
1,First Class,Caribbean,415,94.886840,1.0,234070.244567,29981.189964
7,First Class,Eastern Asia,499,94.822627,1.0,216086.653932,27685.100119
21,First Class,West of USA,398,93.298520,1.0,223375.904362,18610.220048
12,First Class,South America,775,93.206404,1.0,458332.189180,56717.280034

In [52]:
from sqlalchemy import create_engine

In [55]:
engine=create_engine("postgresql://postgres:admin@localhost:host/Logistic_db")
df.to_sql(name='logistic', con=engine, if_exists='replace', index=False)

24

In [57]:
df["Order Id"].duplicated().sum()

np.int64(114767)